### ISSUE TITLE
[Compliment]

### ISSUE THREAD

**Issue by AFrameWorker** [noodlecollie/nightfire-open#37]
Hi, I was looking for Nightfire for PC the other day and I stumbled upon this repo. This is really awesome! Do you have a Discord guild or something where I can follow the progress of this project? I'm highly interested.

**Comment by noodlecollie** [comment]
Thanks! I don't have a Discord because they're not indexable and are too easily lost to time. Anything that concerns the public progress of the project will be kept either in this repo or in the wiki, but bear in mind this is primarily a personal project and so I'm not looking to commit to any public targets at this stage. Anything that is in a playable state will end up on the [releases page](https://github.com/noodlecollie/nightfire-open/releases), though.

**Comment by AFrameWorker** [comment]
Okay, cool! :D
